/* This file is generated by the Makefile.  Don't edit it! */

#ifndef MASTERHASH
#define MASTERHASH "americanmed.hash"
#endif
#ifndef DEFHASH
#define DEFHASH "english.hash"
#endif
#ifndef DEFLANG
#define DEFLANG "english.aff"
#endif
